global:
  scrape_interval: 5s

scrape_configs:
  - job_name: api-service
    static_configs:
      - targets: ["api-service:8000"]

  - job_name: inventory-service
    static_configs:
      - targets: ["inventory-service:8001"]

  - job_name: payment-service
    static_configs:
      - targets: ["payment-service:8002"]
