[SERVICE]
    Flush        1
    Daemon       Off
    Log_Level    info
    Parsers_File parsers.conf

[INPUT]
    Name              tail
    Path              /var/lib/docker/containers/*/*.log
    Parser            docker
    Tag               docker.*
    Refresh_Interval  5
    Mem_Buf_Limit     10MB
    Skip_Long_Lines   On

[FILTER]
    Name          parser
    Match         docker.*
    Key_Name      log
    Parser        json_app
    Reserve_Data  On
    Preserve_Key  On

[OUTPUT]
    Name               es
    Match              docker.*
    Host               elasticsearch
    Port               9200
    Index              observability-logs
    Suppress_Type_Name On
    Retry_Limit        False
