[SERVICE]
    Flush                     1
    Log_Level                 info
    Parsers_File              parsers.conf
    storage.path              /fluent-bit/storage
    storage.sync              normal
    storage.checksum          off
    storage.backlog.mem_limit 10M
    HTTP_Server               On
    HTTP_Listen               0.0.0.0
    HTTP_Port                 2020

[INPUT]
    Name              forward
    Listen            0.0.0.0
    Port              24224
    storage.type      filesystem

[FILTER]
    Name          parser
    Match         tiny-shop.*
    Key_Name      log
    Parser        app_json
    Reserve_Data  On
    Preserve_Key  Off

[FILTER]
    Name   modify
    Match  tiny-shop.*
    Add    project.name tiny-shop
    Add    deployment.environment development
    Copy   service.name service_name

[OUTPUT]
    Name                es
    Match               tiny-shop.*
    Host                elasticsearch
    Port                9200
    Logstash_Format     On
    Logstash_Prefix     tiny-shop
    Suppress_Type_Name  On
    Generate_ID         On
    Replace_Dots        Off
    Retry_Limit         False
    Trace_Error         On

[OUTPUT]
    Name                loki
    Match               tiny-shop.*
    Host                loki
    Port                3100
    Uri                 /loki/api/v1/push
    Labels              project=tiny-shop,environment=development,service_name=$service_name,level=$level
    Line_Format         json
    Auto_Kubernetes_Labels Off
    Retry_Limit         False
